#!/usr/bin/bash

# ===== 3.1. Introduction =====
topdir=$(pwd)
err=0
set -e
chapter=3001
err_report() {
    echo "chapter $chapter: $(date +'%Y.%m.%d %H:%M:%S') Error $? on line $1" | tee >> $topdir/log.txt
}
trap 'err_report $LINENO' ERR
echo "---------" >> $topdir/log.txt
echo chapter $chapter: start = $(date +'%Y.%m.%d %H:%M:%S') >> $topdir/log.txt

if [ "$EUID" -ne "0" ]; then
  echo "ERROR: Please run as root";stop
  exit 1
fi

if [[ -z "${LFS}" ]]; then
  echo "ERROR: 'LFS' is not set.";stop
  exit 1
fi

grep -q ${LFS} /proc/mounts || err=1
if [ "$err" -eq "1" ]; then
  echo "ERROR: The '$LFS' partition must be mounted.";stop
  exit 1
fi

#<p>
#
#  This chapter includes a list of packages that need to be downloaded in order 
# to build a basic Linux system. The listed version numbers correspond to 
# versions of the software that are known to work, and this book is based on 
# their use. We highly recommend against using different versions, because the 
# build commands for one version may not work with a different version, unless 
# the different version is specified by an LFS erratum or security advisory. The 
# newest package versions may also have problems that require work-arounds. These 
# work-arounds will be developed and stabilized in the development version of the 
# book. 
#</p>
#<p>
#
#  For some packages, the release tarball and the (Git or SVN) repository 
# snapshot tarball for that release may be published with similar or even 
# identical file names. But the release tarball may contain some files which are 
# essential despite not stored in the repository (for example, a configure
#  script generated by autoconf
#  ), in addition to the contents of the corresponding repository snapshot. The 
# book uses release tarballs whenever possible. Using a repository snapshot 
# instead of a release tarball specified by the book will cause problems. 
#</p>
#<p>
#
#  Download locations may not always be accessible. If a download location has 
# changed since this book was published, Google ( [https://www.google.com/](https://www.google.com/)
#  ) provides a useful search engine for most packages. If this search is 
# unsuccessful, try one of the alternative means of downloading at [https://www.linuxfromscratch.org/lfs/mirrors.html#files](https://www.linuxfromscratch.org/lfs/mirrors.html#files)
#  . 
#</p>
#<p>
#
#  Downloaded packages and patches will need to be stored somewhere that is 
# conveniently available throughout the entire build. A working directory is also 
# required to unpack the sources and build them. $LFS/sources 
#  can be used both as the place to store the tarballs and patches and as a 
# working directory. By using this directory, the required elements will be 
# located on the LFS partition and will be available during all stages of the 
# building process. 
#</p>
#<p>
#
#  To create this directory, execute the following command, as user root 
#  , before starting the download session: 
#</p>

#********<pre>***********
mkdir -v $LFS/sources
#********</pre>**********
#<p>
#
#  Make this directory writable and sticky. “Sticky”
#  means that even if multiple users have write permission on a directory, only 
# the owner of a file can delete the file within a sticky directory. The 
# following command will enable the write and sticky modes: 
#</p>

#********<pre>***********
chmod -v a+wt $LFS/sources
#********</pre>**********
#<p>
#
#  There are several ways to obtain all the necessary packages and patches to 
# build LFS: 
#</p>

# ***** #<p>
#
#  The files can be downloaded individually as described in the next two 
# sections. 
#</p>

# ***** #<p>
#
#  For stable versions of the book, a tarball of all the needed files can be 
# downloaded from one of the mirror sites listed at [https://www.linuxfromscratch.org/mirrors.html#files](https://www.linuxfromscratch.org/mirrors.html#files)
#  . 
#</p>

# ***** #<p>
#
#  The files can be downloaded using wget
#  and a wget-list as described below. 
#</p>
#<p>
#
#  To download all of the packages and patches by using [wget-list-sysv](../wget-list-sysv)
#  as an input to the wget
#  command, use: 
#</p>

#********<pre>***********
wget --input-file=wget-list-sysv --continue --directory-prefix=$LFS/sources
#********</pre>**********
#<p>
#
#  Additionally, starting with LFS-7.0, there is a separate file, [md5sums](../md5sums)
#  , which can be used to verify that all the correct packages are available 
# before proceeding. Place that file in $LFS/sources 
#  and run: 
#</p>

#********<pre>***********
pushd $LFS/sources
  md5sum -c md5sums
popd
#********</pre>**********
#<p>
#
#  This check can be used after retrieving the needed files with any of the 
# methods listed above. 
#</p>
#<p>
#
#  If the packages and patches are downloaded as a non- root 
#  user, these files will be owned by the user. The file system records the owner 
# by its UID, and the UID of a normal user in the host distro is not assigned in 
# LFS. So the files will be left owned by an unnamed UID in the final LFS system. 
# If you won't assign the same UID for your user in the LFS system, change the 
# owners of these files to root 
#  now to avoid this issue: 
#</p>

#********<pre>***********
chown root:root $LFS/sources/*
#********</pre>**********
echo chapter $chapter: stop  = $(date +'%Y.%m.%d %H:%M:%S') >> $topdir/log.txt
echo "---------" >> $topdir/log.txt
