topdir=$(pwd)
err=0
set -e
chapter=wireless_tools.29
err_report() {
    echo "chapter $chapter: $(date +'%Y.%m.%d %H:%M:%S') Error $? on line $1" | tee >> $topdir/log.txt
}
trap 'err_report $LINENO' ERR
echo "---------" >> $topdir/log.txt
echo chapter $chapter: start = $(date +'%Y.%m.%d %H:%M:%S') >> $topdir/log.txt




srcdir=../../src/wireless_tools.29
tar xf ../../src/wireless_tools.29.tar.gz -C ../../src
# Check, if we could extract the tarball and stop on error:
[ ! -d "$srcdir" ] && stop
cd $srcdir








# Introduction to Wireless Tools
# 
# The Wireless Extension (WE) is a generic API in the Linux kernel allowing a driver to expose configuration and statistics specific to common Wireless LANs to userspace. A single set of tools can support all the variations of Wireless LANs, regardless of their type, as long as the driver supports Wireless Extensions. WE parameters may also be changed on the fly without restarting the driver (or Linux).
# 
# The Wireless Tools (WT) package is a set of tools allowing manipulation of the Wireless Extensions. They use a textual interface to support the full Wireless Extension.
# [Note] Note
# 
# Development versions of BLFS may not build or run some packages properly if LFS or dependencies have been updated since the most recent stable versions of the books.
# Package Information
# 
#     Download (HTTP): https://hewlettpackard.github.io/wireless-tools/wireless_tools.29.tar.gz
# 
#     Download MD5 sum: e06c222e186f7cc013fd272d023710cb
# 
#     Download size: 288 KB
# 
#     Estimated disk space required: 2.0 MB
# 
#     Estimated build time: less than 0.1 SBU
# 
# Additional Downloads
# 
#     Required patch: https://www.linuxfromscratch.org/patches/blfs/svn/wireless_tools-29-fix_iwlist_scanning-1.patch
# 
# Wireless Tools Dependencies
# Required (Runtime)
# 
# Configuring the Linux Kernel for Wireless
# Kernel Configuration
# 
# To use Wireless Tools, the kernel must have the appropriate drivers and other support available. Besides the configurations mentioned by Configuring the Linux Kernel for Wireless, it's also needed to enable the following options in the kernel configuration:
# 
# [*] Networking support --->                                                [NET]
#   [*] Wireless --->                                                   [WIRELESS]
#     <*/M> cfg80211 - wireless configuration API                       [CFG80211]
#     [*]     cfg80211 wireless extensions compatibility           [CFG80211_WEXT]
# 
# Installation of Wireless Tools
# 
# First, apply a patch that fixes a problem when numerous networks are available:

patch -Np1 -i ../wireless_tools-29-fix_iwlist_scanning-1.patch

# To install Wireless Tools, use the following commands:

make -j4

# This package does not come with a test suite.
# 
# Now, as the root user:

make PREFIX=/usr INSTALL_MAN=/usr/share/man install

# Command Explanations
# 
# INSTALL_MAN=/usr/share/man: Install manual pages in /usr/share/man instead of /usr/man.
# Contents
# Installed Programs:
# ifrename, iwconfig, iwevent, iwgetid, iwlist, iwpriv, and iwspy
# Installed Library:
# libiw.so
# Installed Directories:
# None
# Short Descriptions
# 
# ifrename
# 	
# 
# renames network interfaces based on various static criteria
# 
# iwconfig
# 	
# 
# configures a wireless network interface
# 
# iwevent
# 	
# 
# displays wireless events generated by drivers and setting changes
# 
# iwgetid
# 	
# 
# reports ESSID, NWID or AP/Cell Address of wireless networks
# 
# iwlist
# 	
# 
# gets detailed wireless information from a wireless interface
# 
# iwpriv
# 	
# 
# configures optional (private) parameters of a wireless network interface
# 
# iwspy
# 	
# 
# gets wireless statistics from specific node
# 
# libiw.so
# 	
# 
# contains functions required by the wireless programs and provides an API for other programs 
# 








cd $topdir
rm -rf $srcdir
echo chapter $chapter: stop  = $(date +'%Y.%m.%d %H:%M:%S') >> $topdir/log.txt
echo "---------" >> $topdir/log.txt

